public enum Permiso {
    VER_SUCURSALES,
    CREAR_CLIENTE,
    CREAR_CUENTA,
    DAR_BAJA_CUENTA,
    VER_CLIENTES,
    VER_CUENTAS,
    VER_TRANSACCIONES,
    DEPOSITAR_PROPIO,
    RETIRAR_PROPIO,
    TRANSFERIR_PROPIO
}
